- name: Playbook for {{ system }} servers
#  strategy: free
# serial: 3
  hosts: "{{ system }}"
#  gather_facts: "no"
#  any_errors_fatal: true
  vars:
   - zip_name: "Report-{{ system }}-{{ ansible_date_time.date }}.zip"

  tasks:    
    - include: task_ping.yml system_type={{ system }}

    - include: task_copy_objects.yml system_type={{ system }}
    
    - include: task_execute_script.yml system_type={{ system }}
#      register: execution_output
      ignore_errors: yes
#      failed_when: "'ERROR' in execution_output.stdout"
    
    - include: task_retrieve_results.yml system_type={{ system }}
    
    - name: Creating a zip archive on the controller
      archive:
        path: /cygdrive/d/Ansible/repository_results/{{ system }}/*.mef3
        dest: /cygdrive/d/Ansible/repository_results/{{ system }}/{{ zip_name }}
        format: zip
      delegate_to: localhost
      run_once: True
      
    - include: task_eliminate_objects.yml system_type={{ system }}

#     - include: task_send_email.yml
#       run_once: True